### ISSUE TITLE
Ingestion2 process install error

### ISSUE THREAD

**Issue by mjsuhonos** [dpla/automation#117] opened 2015-09-08 20:47 UTC
I'm following the [README-ingestion2](https://github.com/dpla/automation/blob/develop/README-ingestion2.md) document, and everything seems to work fine until I get to this point:

```
ansible-playbook -i ingestion -u <username> dev_ingestion_all.yml --extra-vars "initial_run=true"`
```

Most of the playbook seems to work, but it errors out partway through with:

```
TASK: [postgresql | Ensure state of PostgreSQL networking config file (pg_hba.conf)] *** 
fatal: [dev1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'cms'", 'failed': True}
fatal: [dev1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'cms'", 'failed': True}

FATAL: all hosts have already failed -- aborting
```

Doing  a `vagrant reload` and re-provisioning keeps erring at the same point.  I'm unfortunately new to Ansible, and unfamiliar with the process, so I'm at a bit of a loss as to where to look to troubleshoot this further.  Any help would be greatly appreciated.

**Comment by anarchivist** [comment] 2015-09-08 20:52
Thanks, @mjsuhonos - I think I know the cause of this.

**Comment by mjsuhonos** [comment] 2015-09-08 20:57
I forgot to put in the crystals, didn't I?

![](http://3.bp.blogspot.com/_DGmjKsBO0aE/TTYQ2BcoELI/AAAAAAAAGK0/-wlJLWeB-F8/s1600/napoleon_dynamite_image13.jpg)

**Comment by anarchivist** [comment] 2015-09-09 15:22
@mjsuhonos If you try pulling in the most recently merged changes into the `develop` branch, you should be good to go.

**Comment by mjsuhonos** [comment] 2015-09-09 15:37
:+1: thanks, will confirm later today.

**Comment by mjsuhonos** [comment] 2015-09-10 18:00
Thanks @anarchivist -- this gets further, but now fails with:
```
TASK: [site_proxy | Ensure state of Nginx site config file] ******************* 
fatal: [dev1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'pss'", 'failed': True}
fatal: [dev1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'pss'", 'failed': True}

FATAL: all hosts have already failed -- aborting
```
Similar group handling issue?

**Comment by anarchivist** [comment] 2015-09-10 18:44
Yep. Another fix incoming. :(

**Comment by anarchivist** [comment] 2015-09-14 02:46
@mjsuhonos OK - that should address the issue. Another pull from `develop` should get you sorted.

**Comment by mjsuhonos** [comment] 2015-09-14 19:49
Almost. Now I'm seeing:

```
TASK: [frontend | Update frontend app settings] ******************************* 
fatal: [dev1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'frontend_s3_bucket' is undefined", 'failed': True}
fatal: [dev1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'frontend_s3_bucket' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting
```

**Comment by anarchivist** [comment] 2015-09-14 20:09
@mjsuhonos You'll need to add a value for `frontend_s3_bucket` into `automation/ansible/roles/vars/development.yml`. Sorry about that ... :/

**Comment by mjsuhonos** [comment] 2015-09-15 17:47
Thanks -- uncommenting that line in `automation/ansible/roles/frontend/vars/development.yml` allowed the script to continue.

Now I'm seeing it hang for a long time at:
```
TASK: [frontend | Build frontend app] *****************************************
```

Checking `/tmp/build_frontend.log`, it only contains `starting`, so it looks like `build_frontend.sh` is getting caught [between L9-17](https://github.com/dpla/automation/blob/develop/ansible/roles/frontend/files/build_frontend.sh#L9-L17).

Trying to run the `rbenv` commands manually on dev1 (as vagrant user) gives:
```
The program 'rbenv' is currently not installed.  You can install it by typing:
sudo apt-get install rbenv
```

Ditto on dev2 gives:
```
The program 'rbenv' is currently not installed. To run 'rbenv' please ask your administrator to install the package 'rbenv'
```

But I would expect that to cause the ansible task to fail, no?  Sorry for keeping this open.

**Comment by anarchivist** [comment] 2015-09-15 17:59
@mjsuhonos Re `rbenv`, that only gets install under the `dpla` user, so try `sudo -u dpla -i; rbenv` to make sure it's installed.

**Comment by mjsuhonos** [comment] 2015-09-16 18:12
Thanks; the issue with `build_frontend.sh` was on [line 13](https://github.com/dpla/automation/blob/develop/ansible/roles/frontend/files/build_frontend.sh#L13); `ssh-add` was trying to add a key with a passphrase and silently waiting for input from the local tty.  Using a key without a passphrase solved the issue.  Might be worth a note in the README.

I'm now getting:
```
TASK: [frontend | Start Unicorn] ********************************************** 
failed: [dev1] => {"failed": true}
msg: bundler: command not found: unicorn
Install missing gem executables with `bundle install`

FATAL: all hosts have already failed -- aborting
```

**Comment by anarchivist** [comment] 2015-09-16 23:24
How are you reinvoking `ansible-playbook`  here? Is it the same command, or are you using `--retry`?

**Comment by mjsuhonos** [comment] 2015-09-18 16:28
I'm doing the same as above:
```
ansible-playbook -i ingestion -u <username> dev_ingestion_all.yml --extra-vars "initial_run=true"`
```

When I try with `--retry` added, it tells me there is no such option.

**Comment by anarchivist** [comment] 2015-09-18 21:45
Hi @mjsuhonos - I think a recent commit by @markbreedlove should fix that. Check to make sure that `build_frontend.sh` has `bundle install` in it. You may want to try commenting out the line `bundle update dpla_frontend_assets` that immediately follows it too.

**Comment by mjsuhonos** [comment] 2015-09-29 17:18
@anarchivist trying this after a `git pull` and commenting out `bundle update dpla_frontend_assets` still yields the same error about Unicorn.  `bundle install` is present on line 22 of `build_frontend.sh`.

When I retry with:
```
ansible-playbook -i ingestion -u <username> dev_ingestion_all.yml --extra-vars "initial_run=true" --limit @/Users/mjsuhonos/dev_ingestion_all.retry
```

It gives a different error:
```
TASK: [common | Update hosts file] ******************************************** 
fatal: [dev1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute u'ansible_eth1'", 'failed': True}
fatal: [dev1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute u'ansible_eth1'", 'failed': True}

FATAL: all hosts have already failed -- aborting
```

**Comment by ajhpark** [comment] 2015-10-28 01:57
I'm running into the same error at 
TASK: [frontend | Start Unicorn] ********************************************** 
Is there a fix coming?

**Comment by markbreedlove** [comment] 2015-10-28 13:25
I should be able to look into this within the next day or two.

Could everyone please confirm that:
* You are using the latest version of `automation`?  There was a major release on October 16th that rearranged many variables, and there have been some more since then.  That major release fixed at least one bug related to variable scope.
* With Release 2.x, you are following the installation instructions from the top.  (Note that there's a missing instruction to add the `ubuntu/trusty64` box if you're using Ingestion2, which I'll add later.) You have done `vagrant destroy` on the VMs that didn't get initialized properly, and have created new ones.
* You are not re-running the installation steps after having pulled originally from a 1.x release and then having pulled `development` again with 2.x changes.

I'm working on something else where I'm having to create VMs from scratch and provision them, so I should be able to confirm whether I have any errors with a new installation.  So far, I haven't had any errors but I'm still looking.

**Comment by mjsuhonos** [comment] 2015-10-28 15:35
Hi @markbreedlove -- I'll let @ajhpark confirm the installation steps and VM configuration, but I can confirm that we are working from a recent fork of `automation` here: https://github.com/OurDigitalWorld/automation.

Thanks for the follow-up on this issue; I'm sure you have competing priorities, but we appreciate the help here. Once we have a successful install, I suspect we'll be able to move ahead on our own.

**Comment by ajhpark** [comment] 2015-10-28 18:28
I am fairly sure I can confirm the installation steps.
[This](https://gyazo.com/cf76713a3cee8b11ffc8765f25fb61a3) is what I see in the $LOGFILE that build_frontend.sh writes to
and [this](https://gyazo.com/37fd2c1ea4b97dd3187e4179c0c834e1) is what happens when I manually ssh into the VM, and try to run the commands in the shell. I tried giving all-read permission using chmod to the git_private_key file but that also leads to different errors. Is there a simple solution I am missing?

**Comment by anarchivist** [comment] 2015-10-28 20:29
@ajhpark I believe this is an issue with a private repository, which contains a gem with assets for the frontend. The frontend deployment tasks probably need to changed slightly, but it should be an easy fix.

**Comment by ajhpark** [comment] 2015-10-28 21:22
@anarchivist So will you make the repository public? I'm getting a [similar issue](https://gyazo.com/3a176000256aa6ebab949bdcc8011bce) trying to setup the [frontend](https://github.com/dpla/frontend) as well

**Comment by mjsuhonos** [comment] 2015-10-28 23:56
@ajhpark I assume the repo is private because it contains assets specific to the DPLA that they can't make available.

I'm happy to defer to @anarchivist & @markbreedlove for the moment.

**Comment by anarchivist** [comment] 2015-10-29 17:16
@mjsuhonos is correct. The [frontend application](https://github.com/dpla/frontend) has a way to exempt the restricted assets from the deployment but it looks like we didn't configure the build script to take this under account.

**Comment by markbreedlove** [comment] 2015-10-29 17:47
I will try to submit a PR for that frontend asset change later today.

**Comment by markbreedlove** [comment] 2015-10-29 20:07
Tomorrow morning is now the ETA for that pull request.

**Comment by mjsuhonos** [comment] 2015-10-29 21:29
No worries @markbreedlove -- thank for your attention on this.

**Comment by mjsuhonos** [comment] 2015-10-30 20:42
@markbreedlove - I just tried deploying from [`fix/frontend-deploy-nobranding`](https://github.com/dpla/automation/commit/83f13ab370d1178f141247a46b93a3ba6999238a), and am seeing a new error now:

```
TASK: [frontend | Update frontend app database configuration] ***************** 
fatal: [dev1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'postgresql_user' is undefined", 'failed': True}
fatal: [dev1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'postgresql_user' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting
```

Should this be working currently, or are you still working on the branch?  Apologies if I've jumped the gun.

**Comment by markbreedlove** [comment] 2015-10-30 20:57
@mjsuhonos I haven't run into that, but there haven't been any changes to that branch affecting that variable or how it would be propagated.  Did you copy the `.dist` files mentioned in the https://github.com/dpla/automation/tree/v2.1.3?  You should have a `group_vars/development` file with that variable defined in it: https://github.com/dpla/automation/blob/v2.1.3/ansible/group_vars/development.dist#L32

If you are using the [development](https://github.com/dpla/automation/blob/v2.1.3/ansible/development) or [ingestion](https://github.com/dpla/automation/blob/v2.1.3/ansible/ingestion) inventory, that variable should be defined for all playbooks.

**Comment by ajhpark** [comment] 2015-10-30 21:03
@markbreedlove I'm still getting the same error as before. I've checked the log file and it does run bundle install --without dpla_branding, so it seems that the --without option is not working. Any way to fix this?

**Comment by markbreedlove** [comment] 2015-10-30 21:06
@ajhpark That branch has not been merged yet, so it's somewhat use-at-your-own-risk until it finishes getting reviewed, but, that said, see https://github.com/dpla/automation/blob/fix/frontend-deploy-nobranding/ansible/roles/frontend/files/build_frontend.sh#L11-L17

The best thing I could suggest is doing `vagrant destroy` on the VM (`vagrant destroy dev1` if you're using the `ingestion` inventory) and then `vagrant up` again and the steps performed earlier.

**Comment by ajhpark** [comment] 2015-10-30 21:15
@markbreedlove I've already tried doing vagrant destroy and up. I'll wait for the branch to get reviewed and merged to see if it'll work by then. Thank you for your help and suggestions.

**Comment by markbreedlove** [comment] 2015-10-30 21:52
I've done a test by creating a known-bad ssh keypair and having ansible-playbook use that and I can confirm that I get the same error.  Very frustrating, this Bundler.  It was fetching or testing the existence of dpla_frontend_assets, even though it was excluding it from the list of installed gems.

@anarchivist @AudreyAltman @no-reply  I seem to recall you talking about trying to get Bundler to _really_ not install a particular gem group?  It seems that it wants to fetch gems that are not going to be installed.

**Comment by anarchivist** [comment] 2015-11-03 00:29
Just to give an update, I think this is close to being resolved, but it's probably best to wait until we tag a new release.

**Comment by mjsuhonos** [comment] 2015-11-03 16:08
:+1: thanks again for your support with this issue

**Comment by mjsuhonos** [comment] 2015-11-03 16:18
@markbreedlove sorry about the `.dist` issue above -- it was a filename typo, mea culpa.

**Comment by markbreedlove** [comment] 2015-11-03 16:37
Thanks, @mjsuhonos!  Re the `.dist` issue, no problem.

Here's a new release that we hope will fix the errors you've seen: https://github.com/dpla/automation/releases/tag/v2.1.4

I understand that you're also aware of this:  https://issues.dp.la/issues/8141
At a minimum, I should be able to add some documentation on working around it, until I'm able to look more closely.

**Comment by markbreedlove** [comment] 2015-11-03 16:43
Also, there's going to be another release in a little while for version 2.2.0.  You may want to pull specifically from the 2.1.4 branch if you don't want to have to go through the PostgreSQL 9.4 upgrade.

If you can wait a while and start over with a fresh `dev1` VM, you can wait until the 2.2.0 release and just start with 9.4.

**Comment by mjsuhonos** [comment] 2015-11-03 17:57
Thanks @markbreedlove. Just to confirm, I'm now able to get a mostly-working instance up from the `fix/frontend-deploy-nobranding` branch cloned last week (now appears to be deleted in github).  I'll switch to the `2.1.4` tag and try re-deploying to fresh VMs.

Yes, @anarchivist let me know about the Redmine ticket re: Tomcat, though I can't access that URL publicly.  I can manage manual restarts of Tomcat or otherwise tweaking the VM memory as necessary for the time being.

I suspect that if 2.1.4 works for the time being, then we'll poke around there until 2.2.0 is released.  Our main goal right now is to become familiar with the inner workings of the platform, so as long as `automation` works, we're in good shape.

Thanks again - :heart: DPLA

**Comment by markbreedlove** [comment] 2015-11-04 14:06
Thanks, @mjsuhonos! Sorry about the link to that ticket.  Turns out that the particular issue tracker for infrastructure issues is not public. It basically says that I'm going to either fix the memory issue soon, or write up a workaround in the documentation and follow up on it later if it's going to take more than an hour or two.  I think we should count that as a separate issue from this ticket and close this one out if you're able to get through the installation without error.

**Comment by mjsuhonos** [comment] 2015-11-04 20:51
Yeah, I worked around the memory issue by bumping the memory for `dev2` in `Vagrantfile` to 4GB and reloading the VM.  I can understand why you would want to avoid this extra memory use, but IMO if it's not feasible, then a note in the documentation should suffice.

Regardless, I agree it's a separate issue and this one can probably be closed.  I haven't yet confirmed with @ajhpark that he can get a working stack running, but will do that in the next day or two.

**Comment by markbreedlove** [comment] 2015-11-13 16:02
Hi, just want to check whether anyone objects to me closing this. Since this ticket covers the installation errors, we should open further tickets if there are still memory-related problems or whatever.

**Comment by mjsuhonos** [comment] 2015-11-13 16:12
Yes, sorry for not following up on this.  Considering it resolved, thanks again.

**Comment by markbreedlove** [comment] 2015-11-13 16:57
OK, thanks!

**Closed by markbreedlove** 2015-11-13 16:57 UTC
Labels: bug
